### ISSUE TITLE
add xtask to aya-template

### ISSUE THREAD

**Issue by endepointe** [aya-rs/book#183] opened 2024-11-25 02:45 UTC
Hey rustaceans. I went through the setup, using the aya-template and I am curious why the xtask is not part of the template? Also, why is cargo-xtask not referenced in the tutorials https://aya-rs.dev/book/start/ ?  There are a few crates that reference xtask* so it was rather confusing at first to know what xtask package was being referred to in the xdp-hello example.

This issue is a *nice-to-have* or *documentation* label.

Thanks for the future feedback!

**Comment by endepointe** [comment] 2024-11-25 04:13
User-defined aliases will become errors in the future if using cargo-xtask so how will aya minimize this issue?

```bash
cargo xtask run -- -h                                                                                                                                                                            
warning: user-defined alias `xtask` is shadowing an external subcommand found at: `/home/ende/.cargo/bin/cargo-xtask`                                                                                                                         
This was previously accepted but is being phased out; it will become a hard error in a future release.                                                                                                                                        
For more information, see issue #10049 <https://github.com/rust-lang/cargo/issues/10049>.     
```

**Comment by tamird** [comment] 2024-11-26 15:47
Closing as duplicate of #176.

**Closed by tamird** 2024-11-26 15:47 UTC
